#community_bridge: LinuxAppStore
patreon: linuxappstore
#custom: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=freesunfury@gmail.com&lc=GB&item_name=Linux%20App%20Store&currency_code=USD&no_note=0&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHostedGuest
